### ISSUE TITLE
Update TokenSearchIndex implementation to ignore punctuation in matching

### ISSUE THREAD

**Issue by jakemannix** [industrycrashcourse/dummyjvm#23]
We'd like the search() method to accept queries like "foo" and match documents like "I say foo! to you", as well as queries like "joe bob" to match "My name is joe-bob, don't you know that?".

Similarly, if you query for the string "foo!" you should ignore the "!" and match a document like "I say foo to you".

Searching the web finds code snippets like this: https://www.programcreek.com/java-api-examples/?class=java.lang.Character&method=OTHER_PUNCTUATION

**Comment by dasar208** [comment]
Needs to work on having a shared design for implementing whatever kind of manipulation of query
