### ISSUE TITLE
Support multi-word matching

### ISSUE THREAD

**Issue by jakemannix** [industrycrashcourse/dummyjvm#27]
queries like "quick fox" should match "the quick brown fox jumps", and "that fox sure is quick"

extra credit: if several words are surrounded by DOUBLE quotes, at query time, treat them as a single word: "quick 'brown fox' jumps" should match "The quick fellow is not a brown fox but he sure jumps", but should not match "The quick fellow is not a brown rabbit but is a fox who jumps".

**Comment by tylerastraub** [comment]
i'm already seeing an issue with the single quotes, for instance if someone searches "it's tyler's job", that would incorrectly count "s tyler" as one word. i don't know what the final product is still but i know that most people who use google don't use specific search tools, so i'd imagine this would be an issue more than it would help. should we use a different character to identify this, such as parentheses, or for the purposes of this assignment should we ignore it? backslashes or a character combo that identifies it could be other alternatives

**Comment by jakemannix** [comment]
Right, so this is a question of the product requirement.  Maybe for now, ignoring the special parsing of any strings with an odd number of ' characters is fine.

**Comment by jakemannix** [comment]
You could switch to using double quotes, but then you need to deal with the fact that in java, you'd need to escape the " character with a backslash

**Comment by dasar208** [comment]
Parking lot: Think about pausing on some of your development and try to encode some of your logic in failing tests so we can make sure once you get it working it will work. Otherwise your test is tailored to what you already did which is not very effective
