### ISSUE TITLE
Support "OR" querying

### ISSUE THREAD

**Issue by jakemannix** [industrycrashcourse/dummyjvm#28]
Queries containing the token OR should be treated differently:

"foo OR bar" should match all of the following documents: "My name is foo", "I really like foo bar juice", and "I'm going to the bar"

Multiple OR's should also be respected:

"foo OR bar OR baz" should match any docs containing any of the words, and so on, for any number of OR's

**Comment by dasar208** [comment]
Parking lot note: Make sure we get a chance to do a shared code review on your code since you are a bit further along than others.
